"""企业入库表单（通用字段 + 行业专项字段）配置。"""

ENTRY_SOURCE_OPTIONS = ["主动报名", "政府推荐", "协会推荐", "展会获取", "老客户推荐", "网络收集", "其他"]
ENTRY_STAGE_OPTIONS = ["初步接触", "资料收集中", "已完成初审", "已推荐客户", "撮合中"]
ENTERPRISE_DEFAULT_STATUS = "已入库"

COMMON_ENTERPRISE_FIELD_GROUPS = [
    {
        "key": "A",
        "title": "A. 基本信息",
        "fields": [
            {"key": "enterprise_code", "label": "企业编号", "type": "text", "required": True, "placeholder": "请手动输入企业编号", "col_class": "col-lg-6"},
            {"key": "project_owner", "label": "项目负责人", "type": "text", "col_class": "col-lg-6"},
            {"key": "company_full_name", "label": "企业全称", "type": "text", "required": True, "col_class": "col-lg-6"},
            {"key": "english_name", "label": "英文名称", "type": "text", "col_class": "col-lg-6"},
            {"key": "industry_code", "label": "行业大类", "type": "industry_select", "required": True, "col_class": "col-lg-6"},
            {"key": "sub_industry", "label": "细分行业", "type": "text", "placeholder": "请选择或填写细分行业", "col_class": "col-lg-6"},
            {"key": "province", "label": "省份", "type": "text", "placeholder": "例如：广东省", "col_class": "col-lg-6"},
            {"key": "city", "label": "城市", "type": "text", "placeholder": "例如：深圳市", "col_class": "col-lg-6"},
            {"key": "financing_stage", "label": "融资阶段", "type": "select", "options": ["未融资", "天使轮", "Pre-A轮", "A轮", "B轮", "C轮", "D轮及以后", "战略融资", "已上市", "未披露"], "col_class": "col-lg-6"},
            {"key": "employee_count_range", "label": "人员规模", "type": "select", "options": ["1-20人", "21-50人", "51-100人", "101-300人", "301-500人", "501-1000人", "1000人以上", "未披露"], "col_class": "col-lg-6"},
            {"key": "core_products", "label": "核心产品", "type": "textarea", "placeholder": "请填写企业核心产品，例如：工业传感器、控制模块", "span_full_row": True},
            {"key": "website", "label": "企业网址", "type": "url", "placeholder": "http://example.com", "span_full_row": True},
            {"key": "enterprise_description", "label": "企业介绍", "type": "textarea", "maxlength": 1000, "span_full_row": True, "placeholder": "请填写企业介绍"},
            {"key": "enterprise_tags", "label": "企业标签", "type": "checkbox_tags", "allow_custom": True, "options": ["医疗服务", "医疗健康", "康复机构", "民营专科医疗机构", "数字疗法", "非公医疗机构", "数字医疗", "健康管理", "医疗卫生机构", "康复训练"]},
        ],
    },
    {
        "key": "B",
        "title": "B. 工商信息",
        "fields": [
            {"key": "registered_name", "label": "注册名称", "type": "text", "placeholder": "默认等于企业全称，可手动修改"},
            {"key": "company_type", "label": "企业类型", "type": "text", "required": True, "placeholder": "例如：有限责任公司"},
            {"key": "unified_social_credit_code", "label": "统一社会信用代码", "type": "text", "required": True, "placeholder": "18位统一社会信用代码", "help_text": "格式提示：18位数字或大写字母组合。"},
            {"key": "legal_representative", "label": "法定代表人", "type": "text", "required": True},
            {"key": "registered_capital", "label": "注册资本", "type": "text", "required": True},
            {"key": "founded_date", "label": "成立日期", "type": "date", "required": True},
            {"key": "business_term_start", "label": "营业期限起始日期", "type": "date", "required": True},
            {"key": "business_term_end", "label": "营业期限终止日期", "type": "date", "placeholder": "无终止日期可不填"},
            {"key": "registered_address", "label": "注册地址", "type": "text", "required": True},
            {"key": "business_scope", "label": "经营范围", "type": "textarea", "maxlength": 2000, "span_full_row": True, "placeholder": "请填写营业执照经营范围"},
        ],
    },
    {
        "key": "C",
        "title": "C. 联系信息",
        "fields": [
            {"key": "primary_contact_name", "label": "主联系人姓名", "type": "text"},
            {"key": "primary_contact_position", "label": "职位", "type": "select_or_text", "options": ["董事长", "总经理", "外贸负责人", "销售负责人", "项目对接人", "其他"]},
            {"key": "primary_contact_mobile", "label": "手机", "type": "text", "placeholder": "例如：13800138000", "help_text": "请输入 11 位手机号。"},
            {"key": "contact_phone", "label": "电话", "type": "text"},
            {"key": "contact_email", "label": "邮箱", "type": "email", "placeholder": "name@example.com", "help_text": "格式示例：name@example.com。"},
            {"key": "official_account", "label": "公众号", "type": "text"},
            {"key": "dynamic_contacts", "label": "联系人子表单", "type": "dynamic_contacts"},
        ],
    },
    {
        "key": "D",
        "title": "D. 经营情况",
        "fields": [
            {
                "key": "enterprise_natures",
                "label": "企业性质（多选）",
                "type": "checkbox_group",
                "options": ["制造商", "贸易商", "品牌商", "代理商", "服务商", "OEM/ODM工厂"],
            },
            {"key": "is_listed_or_pre_ipo", "label": "是否上市", "type": "radio_group", "options": ["是", "否"]},
            {"key": "listed_location", "label": "上市地点", "type": "text", "show_when": {"field": "is_listed_or_pre_ipo", "value": "是"}},
            {"key": "listed_board", "label": "上市板块", "type": "text", "show_when": {"field": "is_listed_or_pre_ipo", "value": "是"}},
            {"key": "business_address", "label": "实际经营地址", "type": "text"},
            {"key": "business_directions", "label": "主营业务方向", "type": "checkbox_tags", "options": ["制造", "贸易", "工程", "服务", "渠道", "跨境电商"], "help_text": "建议最多选择 3 项。"},
            {"key": "customer_types", "label": "主要客户类型", "type": "checkbox_tags", "options": ["品牌商", "进口商", "经销商", "批发商", "零售商", "商超", "工程商", "政府", "电商卖家"]},
            {"key": "domestic_regions", "label": "主要销售区域（国内）", "type": "checkbox_tags", "options": ["华东", "华南", "华北", "华中", "西南", "西北", "东北", "全国"]},
            {"key": "has_overseas_business", "label": "是否已有海外业务", "type": "radio_group", "options": ["是", "否"]},
            {"key": "overseas_regions", "label": "海外市场区域", "type": "checkbox_tags", "options": ["东南亚", "东亚", "南亚", "中东", "欧洲", "北美", "南美", "非洲", "大洋洲"], "show_when": {"field": "has_overseas_business", "value": "是"}},
            {"key": "sales_channels", "label": "主要销售渠道", "type": "checkbox_tags", "options": ["直销", "经销", "代理", "电商平台", "独立站", "展会", "工程项目"]},
            {"key": "cooperation_preferences", "label": "合作偏好", "type": "checkbox_tags", "options": ["渠道合作", "OEM", "ODM", "联合开发", "技术合作", "资本合作", "代理分销"]},
        ],
    },
    {
        "key": "E",
        "title": "E. 生产能力",
        "fields": [
            {"key": "has_own_factory", "label": "是否自有工厂", "type": "radio_group", "options": ["是", "否", "部分自有"]},
            {"key": "production_mode", "label": "生产模式", "type": "checkbox_tags", "options": ["自主生产", "委外加工", "组装", "混合模式"]},
            {"key": "factory_count", "label": "工厂数量", "type": "radio_group", "options": ["1家", "2-3家", "4-5家", "5家以上"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "factory_area_range", "label": "厂房面积", "type": "radio_group", "options": ["500㎡以下", "500～1000㎡", "1000～3000㎡", "3000～5000㎡", "5000以上㎡"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "production_line_count", "label": "产线数量", "type": "radio_group", "options": ["1-5条", "6-10条", "11-20条", "20条以上"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "has_rnd_team", "label": "是否有研发团队", "type": "radio_group", "options": ["是", "否"]},
            {"key": "rnd_team_size", "label": "研发团队规模", "type": "radio_group", "options": ["1-30", "30-50", "50-100", "100+"], "show_when": {"field": "has_rnd_team", "value": "是"}},
            {"key": "supports_sampling", "label": "是否支持打样", "type": "radio_group", "options": ["是", "否"]},
            {"key": "sampling_cycle", "label": "打样周期", "type": "radio_group", "options": ["3天内", "1周内", "2周内", "2周以上", "视需求而定"], "show_when": {"field": "supports_sampling", "value": "是"}},
            {"key": "supports_customization", "label": "是否支持定制", "type": "checkbox_tags", "options": ["OEM", "ODM", "包装定制", "LOGO定制", "联合开发", "不支持"]},
            {"key": "delivery_capability_tags", "label": "交付能力标签", "type": "checkbox_tags", "options": ["小单灵活", "大单稳定", "快速交付", "柔性生产", "高标准质检"]},
            {"key": "has_qc_process", "label": "是否有质量管理流程", "type": "radio_group", "options": ["是", "否", "未核验"]},
            {"key": "qc_methods", "label": "质量控制方式", "type": "checkbox_tags", "options": ["来料检验", "过程检验", "出货检验", "全检", "抽检", "第三方检测"], "show_when": {"field": "has_qc_process", "value": "是"}},
            {"key": "stable_outsourcing_factory", "label": "稳定代工厂情况", "type": "textarea", "maxlength": 100, "placeholder": "100字以内", "help_text": "请控制在100字以内。", "show_when": {"field": "has_own_factory", "value": "否"}},
        ],
    },
    {
        "key": "F",
        "title": "F. 外贸能力",
        "fields": [
            {"key": "export_experience", "label": "是否有出口经验", "type": "radio_group", "options": ["是", "否"]},
            {"key": "first_export_year", "label": "首次出口年份", "type": "year", "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "foreign_trade_team_size", "label": "外贸团队规模", "type": "radio_group", "options": ["1-30", "30-50", "50-100", "100+"]},
            {"key": "major_export_regions", "label": "主要出口区域", "type": "checkbox_tags", "options": ["东南亚", "欧洲", "北美", "南美", "中东", "非洲", "日本韩国", "澳新"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "export_country_count", "label": "出口国家数量", "type": "radio_group", "options": ["1-3", "4-10", "11-30", "30+"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "trade_terms", "label": "常用贸易术语", "type": "checkbox_tags", "options": ["EXW", "FOB", "CIF", "DDP", "DAP", "FCA"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "payment_methods", "label": "常用付款方式", "type": "checkbox_tags", "options": ["T/T", "L/C", "OA", "D/P", "其他"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "has_english_materials", "label": "是否具备英文资料", "type": "radio_group", "options": ["是", "否", "部分具备"]},
            {"key": "attended_international_expo", "label": "是否参加过国际展会", "type": "radio_group", "options": ["是", "否"]},
            {"key": "international_expo_names", "label": "国际展会名称", "type": "text", "show_when": {"field": "attended_international_expo", "value": "是"}},
            {"key": "has_cross_border_ecommerce", "label": "是否有跨境电商经验", "type": "radio_group", "options": ["是", "否"]},
            {"key": "cross_border_platforms", "label": "跨境平台布局", "type": "checkbox_tags", "options": ["阿里国际站", "中国制造网", "Amazon", "eBay", "TikTok Shop", "独立站", "其他"], "show_when": {"field": "has_cross_border_ecommerce", "value": "是"}},
            {"key": "overseas_warehouse", "label": "是否有海外仓", "type": "radio_group", "options": ["是", "否", "合作海外仓"]},
            {"key": "overseas_after_sales", "label": "是否有境外售后能力", "type": "radio_group", "options": ["是", "否", "依赖合作方"]},
            {"key": "export_docs_familiarity", "label": "是否熟悉进出口单证", "type": "radio_group", "options": ["是", "否", "需辅导"]},
            {"key": "target_expansion_markets", "label": "拟拓展市场", "type": "checkbox_tags", "options": ["东南亚", "欧洲", "北美", "中东", "非洲", "南美", "其他"], "show_when": {"field": "export_experience", "value": "否"}},
            {"key": "foreign_trade_support_needs", "label": "是否需要外贸支持", "type": "checkbox_tags", "options": ["英文资料", "客户开发", "报价辅导", "物流单证", "认证合规", "展会推荐"], "show_when_any": [{"field": "export_experience", "value": "否"}, {"field": "foreign_trade_team_size", "value": ["1-30"]}]},
        ],
    },
    {
        "key": "G",
        "title": "G. 财务信用",
        "fields": [
            {"key": "annual_revenue_range", "label": "年营业收入区间", "type": "radio_group", "options": ["500万以下", "500万-2000万", "2000万-1亿", "1亿-5亿", "5亿以上", "不便披露"]},
            {"key": "annual_export_amount_range", "label": "年出口额区间", "type": "radio_group", "options": ["无", "100万以下", "100万-1000万", "1000万-1亿", "1亿以上", "不便披露"]},
            {"key": "tax_credit_level", "label": "纳税信用等级", "type": "radio_group", "options": ["A", "B", "C", "D", "未知"]},
            {"key": "can_provide_audit_report", "label": "是否可提供审计报表", "type": "radio_group", "options": ["是", "否", "视合作阶段提供"]},
            {"key": "has_bank_credit_line", "label": "是否有银行授信", "type": "radio_group", "options": ["是", "否", "未知"]},
            {"key": "has_major_litigation", "label": "是否存在重大诉讼", "type": "radio_group", "options": ["是", "否", "未核验"]},
        ],
    },
    {
        "key": "H",
        "title": "H. 资质合规",
        "fields": [
            {"key": "has_import_export_qualification", "label": "是否具备进出口相关资质", "type": "radio_group", "options": ["是", "否", "未确认"]},
            {"key": "operation_production_qualifications", "label": "经营/生产资质", "type": "checkbox_tags", "options": ["营业执照", "生产许可证", "食品生产许可", "医疗器械许可", "危化许可", "特种设备许可", "其他"]},
            {"key": "management_system_certifications", "label": "管理体系认证", "type": "checkbox_tags", "options": ["ISO9001", "ISO14001", "ISO45001", "BSCI", "Sedex", "IATF16949", "ISO13485", "HACCP", "GMP"]},
            {"key": "intellectual_property_status", "label": "知识产权情况", "type": "checkbox_tags", "options": ["商标", "发明专利", "实用新型", "外观专利", "软件著作权", "无", "未核验"]},
            {"key": "compliance_declarations", "label": "合规声明", "type": "checkbox_tags", "options": ["环保合规", "劳工合规", "反商业贿赂", "数据真实性", "无重大违法记录"]},
            {"key": "certificate_completeness", "label": "证书是否齐全", "type": "radio_group", "options": ["齐全", "基本齐全", "待补充", "未核验"]},
            {"key": "certificate_validity_status", "label": "证书有效期状态", "type": "radio_group", "options": ["全部有效", "部分临期", "部分过期", "未核验"]},
            {"key": "qualification_notes", "label": "资质补充说明", "type": "textarea", "maxlength": 200, "placeholder": "200字以内"},
        ],
    },
]


from config.industry_config import INDUSTRY_EXTRA_FIELD_CONFIG
