"""企业入库表单（通用字段 + 行业专项字段）配置。"""

COMMON_ENTERPRISE_FIELD_GROUPS = [
    {
        "key": "A",
        "title": "A. 企业身份",
        "fields": [
            {"key": "company_full_name", "label": "企业全称", "type": "text", "required": True},
            {"key": "english_name", "label": "英文名称", "type": "text"},
            {"key": "unified_social_credit_code", "label": "统一社会信用代码", "type": "text"},
            {"key": "registered_address", "label": "注册地址", "type": "text"},
            {"key": "business_address", "label": "实际经营地址", "type": "text"},
            {"key": "founded_date", "label": "成立时间", "type": "date"},
            {"key": "registered_capital", "label": "注册资本", "type": "text"},
        ],
    },
    {
        "key": "B",
        "title": "B. 企业性质",
        "fields": [
            {
                "key": "enterprise_natures",
                "label": "企业性质（多选）",
                "type": "checkbox_group",
                "options": ["制造商", "贸易商", "品牌商", "代理商", "服务商", "OEM/ODM工厂"],
            }
        ],
    },
    {
        "key": "C",
        "title": "C. 联系信息",
        "fields": [
            {"key": "primary_contact_name", "label": "主联系人姓名", "type": "text", "required": True},
            {"key": "primary_contact_position", "label": "职位", "type": "select_or_text", "required": True, "options": ["董事长", "总经理", "外贸负责人", "销售负责人", "项目对接人", "其他"]},
            {"key": "primary_contact_mobile", "label": "手机", "type": "text", "required": True, "placeholder": "例如：13800138000", "help_text": "请输入 11 位手机号。"},
            {"key": "contact_phone", "label": "电话", "type": "text"},
            {"key": "contact_email", "label": "邮箱", "type": "email", "placeholder": "name@example.com", "help_text": "格式示例：name@example.com。"},
            {"key": "wechat", "label": "微信", "type": "text"},
            {"key": "language_skills", "label": "语言能力", "type": "checkbox_tags", "options": ["中文", "英文", "日语", "韩语", "俄语", "西班牙语", "其他"]},
            {"key": "english_communication", "label": "是否可直接英文沟通", "type": "radio_group", "options": ["是", "否", "需翻译协助"]},
            {"key": "website", "label": "官网", "type": "url", "placeholder": "https://example.com", "help_text": "请填写完整 URL（含 http:// 或 https://）。"},
            {"key": "official_account", "label": "公众号", "type": "text"},
            {"key": "linkedin", "label": "LinkedIn", "type": "text"},
            {"key": "enterprise_email", "label": "企业邮箱", "type": "text"},
            {"key": "dynamic_contacts", "label": "联系人子表单", "type": "dynamic_contacts"},
        ],
    },
    {
        "key": "D",
        "title": "D. 经营情况",
        "fields": [
            {"key": "business_directions", "label": "主营业务方向", "type": "checkbox_tags", "required": True, "options": ["制造", "贸易", "工程", "服务", "渠道", "跨境电商"], "help_text": "建议最多选择 3 项。"},
            {"key": "main_business", "label": "主要业务描述", "type": "textarea", "placeholder": "200字以内"},
            {"key": "customer_types", "label": "主要客户类型", "type": "checkbox_tags", "options": ["品牌商", "进口商", "经销商", "批发商", "零售商", "商超", "工程商", "政府", "电商卖家"]},
            {"key": "domestic_regions", "label": "主要销售区域（国内）", "type": "checkbox_tags", "options": ["华东", "华南", "华北", "华中", "西南", "西北", "东北", "全国"]},
            {"key": "has_overseas_business", "label": "是否已有海外业务", "type": "radio_group", "required": True, "options": ["是", "否"]},
            {"key": "overseas_regions", "label": "海外市场区域", "type": "checkbox_tags", "options": ["东南亚", "东亚", "南亚", "中东", "欧洲", "北美", "南美", "非洲", "大洋洲"], "show_when": {"field": "has_overseas_business", "value": "是"}},
            {"key": "sales_channels", "label": "主要销售渠道", "type": "checkbox_tags", "options": ["直销", "经销", "代理", "电商平台", "独立站", "展会", "工程项目"]},
            {"key": "has_long_term_key_clients", "label": "是否有长期大客户", "type": "radio_group", "options": ["是", "否", "不便披露"]},
            {"key": "customer_stability", "label": "客户稳定性", "type": "radio_group", "options": ["高", "中", "低", "未核验"]},
            {"key": "has_own_brand_business", "label": "是否有自有品牌业务", "type": "radio_group", "options": ["是", "否"]},
            {"key": "cooperation_preferences", "label": "合作偏好", "type": "checkbox_tags", "options": ["渠道合作", "OEM", "ODM", "联合开发", "技术合作", "资本合作", "代理分销"]},
        ],
    },
    {
        "key": "E",
        "title": "E. 生产能力",
        "fields": [
            {"key": "has_own_factory", "label": "是否自有工厂", "type": "radio_group", "required": True, "options": ["是", "否", "部分自有"]},
            {"key": "production_mode", "label": "生产模式", "type": "checkbox_tags", "options": ["自主生产", "委外加工", "组装", "混合模式"]},
            {"key": "factory_count", "label": "工厂数量", "type": "radio_group", "options": ["1家", "2-3家", "4-5家", "5家以上"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "factory_area_range", "label": "厂房面积", "type": "radio_group", "options": ["500㎡以下", "500-2000㎡", "2000-5000㎡", "5000-10000㎡", "10000㎡以上"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "employee_count_range", "label": "生产员工人数", "type": "radio_group", "options": ["20以下", "20-50", "51-100", "101-300", "300+"], "show_when": {"field": "has_own_factory", "value": ["是", "部分自有"]}},
            {"key": "has_rnd_team", "label": "是否有研发团队", "type": "radio_group", "options": ["是", "否"]},
            {"key": "rnd_team_size", "label": "研发团队规模", "type": "radio_group", "options": ["1-5", "6-10", "11-20", "20+"], "show_when": {"field": "has_rnd_team", "value": "是"}},
            {"key": "supports_sampling", "label": "是否支持打样", "type": "radio_group", "options": ["是", "否"]},
            {"key": "sampling_cycle", "label": "打样周期", "type": "radio_group", "options": ["3天内", "1周内", "2周内", "2周以上", "视需求而定"], "show_when": {"field": "supports_sampling", "value": "是"}},
            {"key": "supports_customization", "label": "是否支持定制", "type": "checkbox_tags", "options": ["OEM", "ODM", "包装定制", "LOGO定制", "联合开发", "不支持"]},
            {"key": "delivery_capability_tags", "label": "交付能力标签", "type": "checkbox_tags", "options": ["小单灵活", "大单稳定", "快速交付", "柔性生产", "高标准质检"]},
            {"key": "has_qc_process", "label": "是否有质量管理流程", "type": "radio_group", "options": ["是", "否", "未核验"]},
            {"key": "qc_methods", "label": "质量控制方式", "type": "checkbox_tags", "options": ["来料检验", "过程检验", "出货检验", "全检", "抽检", "第三方检测"], "show_when": {"field": "has_qc_process", "value": "是"}},
            {"key": "stable_outsourcing_factory", "label": "稳定代工厂情况", "type": "textarea", "maxlength": 100, "placeholder": "100字以内", "help_text": "请控制在100字以内。", "show_when": {"field": "has_own_factory", "value": "否"}},
        ],
    },
    {
        "key": "F",
        "title": "F. 外贸能力",
        "fields": [
            {"key": "export_experience", "label": "是否有出口经验", "type": "radio_group", "required": True, "options": ["是", "否"]},
            {"key": "first_export_year", "label": "首次出口年份", "type": "year", "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "foreign_trade_team_size", "label": "外贸团队规模", "type": "radio_group", "options": ["无", "1-3人", "4-10人", "10人以上"]},
            {"key": "major_export_regions", "label": "主要出口区域", "type": "checkbox_tags", "options": ["东南亚", "欧洲", "北美", "南美", "中东", "非洲", "日本韩国", "澳新"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "export_country_count", "label": "出口国家数量", "type": "radio_group", "options": ["1-3", "4-10", "11-30", "30+"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "trade_terms", "label": "常用贸易术语", "type": "checkbox_tags", "options": ["EXW", "FOB", "CIF", "DDP", "DAP", "FCA"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "payment_methods", "label": "常用付款方式", "type": "checkbox_tags", "options": ["T/T", "L/C", "OA", "D/P", "其他"], "show_when": {"field": "export_experience", "value": "是"}},
            {"key": "has_english_materials", "label": "是否具备英文资料", "type": "radio_group", "options": ["是", "否", "部分具备"]},
            {"key": "english_communication", "label": "是否具备英文沟通能力", "type": "radio_group", "options": ["是", "否", "需协助"]},
            {"key": "attended_international_expo", "label": "是否参加过国际展会", "type": "radio_group", "options": ["是", "否"]},
            {"key": "international_expo_names", "label": "国际展会名称", "type": "text", "show_when": {"field": "attended_international_expo", "value": "是"}},
            {"key": "has_cross_border_ecommerce", "label": "是否有跨境电商经验", "type": "radio_group", "options": ["是", "否"]},
            {"key": "cross_border_platforms", "label": "跨境平台布局", "type": "checkbox_tags", "options": ["阿里国际站", "中国制造网", "Amazon", "eBay", "TikTok Shop", "独立站", "其他"], "show_when": {"field": "has_cross_border_ecommerce", "value": "是"}},
            {"key": "overseas_warehouse", "label": "是否有海外仓", "type": "radio_group", "options": ["是", "否", "合作海外仓"]},
            {"key": "overseas_after_sales", "label": "是否有境外售后能力", "type": "radio_group", "options": ["是", "否", "依赖合作方"]},
            {"key": "export_docs_familiarity", "label": "是否熟悉进出口单证", "type": "radio_group", "options": ["是", "否", "需辅导"]},
            {"key": "target_expansion_markets", "label": "拟拓展市场", "type": "checkbox_tags", "options": ["东南亚", "欧洲", "北美", "中东", "非洲", "南美", "其他"], "show_when": {"field": "export_experience", "value": "否"}},
            {"key": "foreign_trade_support_needs", "label": "是否需要外贸支持", "type": "checkbox_tags", "options": ["英文资料", "客户开发", "报价辅导", "物流单证", "认证合规", "展会推荐"], "show_when_any": [{"field": "export_experience", "value": "否"}, {"field": "foreign_trade_team_size", "value": ["无", "1-3人"]}]},
        ],
    },
    {
        "key": "G",
        "title": "G. 财务信用",
        "fields": [
            {"key": "tax_certificate", "label": "纳税证明", "type": "select", "options": ["已提供", "未提供", "不适用"]},
            {"key": "credit_report", "label": "企业信用报告", "type": "select", "options": ["已提供", "未提供", "不适用"]},
            {"key": "litigation_status", "label": "涉诉情况", "type": "select", "options": ["无", "有", "待核查"]},
            {"key": "penalty_status", "label": "行政处罚情况", "type": "select", "options": ["无", "有", "待核查"]},
            {"key": "bank_credit_certificate", "label": "银行资信证明", "type": "select", "options": ["已提供", "未提供", "不适用"]},
        ],
    },
    {
        "key": "H",
        "title": "H. 合作意愿",
        "fields": [
            {"key": "target_countries", "label": "希望拓展国家", "type": "textarea"},
            {"key": "target_client_types", "label": "目标客户类型", "type": "checkbox_group", "options": ["进口商", "经销商", "品牌商", "工程商", "平台卖家", "政府采购", "终端客户", "其他"]},
            {"key": "cooperation_models", "label": "可接受合作模式", "type": "checkbox_group", "options": ["批发", "代理", "OEM", "ODM", "项目制", "跨境电商", "联合品牌", "其他"]},
            {"key": "minimum_order_quantity", "label": "最低订单量", "type": "text"},
            {"key": "price_flexibility", "label": "价格弹性", "type": "select", "options": ["强", "中", "弱", "暂未确认"]},
            {"key": "material_completeness", "label": "资料完整度", "type": "select", "options": ["A类资料完整", "B类资料较完整", "资料缺失较多", "待补充"]},
            {"key": "other_notes", "label": "其他说明", "type": "textarea"},
        ],
    },
]


from config.industry_config import INDUSTRY_EXTRA_FIELD_CONFIG
